In [1]:
import numpy as np

In [2]:
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

print(temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [6]:
print(temperatures_w1.shape)

(7,)


In [10]:
print(temperatures_w1.dtype)

float64


In [11]:
print(temperatures_w1.size)

7


In [12]:
Fahrenheit=(temperatures_w1*9/5)+32
print(Fahrenheit)

[72.5  77.54 69.44 74.12 78.98 76.64 71.42]


In [14]:
print("maximum",temperatures_w1.max())
print("minimum",temperatures_w1.min())
print("mean",temperatures_w1.mean())


maximum 26.1
minimum 20.8
mean 23.542857142857144


In [15]:
print(temperatures_w1[:3])

[22.5 25.3 20.8]


In [17]:
print(temperatures_w1[-2:])

[24.8 21.9]


In [18]:
print(temperatures_w1[2:5])

[20.8 23.4 26.1]


In [19]:
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])

print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [20]:
print("Shape:", temperatures.shape)
print("Data type:", temperatures.dtype)
print("Number of elements:", temperatures.size)

Shape: (2, 7)
Data type: float64
Number of elements: 14


In [21]:
print(temperatures[0])

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [22]:
print(temperatures[1])

[19.2 22.5 21.3 24.  23.5 22.8 20.1]


In [23]:
print(temperatures[:, -2:])

[[24.8 21.9]
 [22.8 20.1]]


In [24]:
import pandas as pd

In [25]:
marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [26]:
print(marks.iloc[0])

95


In [27]:
print(marks.loc[['Rank1', 'Rank2', 'Rank3']])

Rank1    95
Rank2    92
Rank3    89
dtype: int64


In [28]:
print(marks.iloc[2])

89


In [29]:
print(marks[marks > 90])

Rank1    95
Rank2    92
dtype: int64


In [30]:
marks.loc['Rank1'] = 100

print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64


In [31]:
marks = marks.drop('Rank5')

print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64


In [32]:
cgpa = marks / 10

print(cgpa)

Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


In [40]:
transaction=pd.DataFrame({
    "TransactionID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
                         "ProductCategory": ['Electronics', 'Clothing', 'Electronics', 'Furniture',
'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
                         "Region": ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West',
'South', 'North'],
                         "Amount":[ 200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
    })
print(transaction)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [41]:
print(transaction.head())

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200


In [42]:
print(transaction.tail())

   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [44]:
print(transaction.shape)

(10, 4)


In [46]:
print(transaction.columns)

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')


In [48]:
print(transaction.dtypes)

TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object


In [52]:
print(transaction[["ProductCategory","Amount"]])

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400


In [54]:
print(transaction.iloc[:,-3:])

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400


In [58]:
filtered = transaction[
    (transaction['Region'] == 'North') &
    (transaction['Amount'] > 200)
]

print(filtered)

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400


In [60]:
print(transaction['ProductCategory'].value_counts())

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


In [61]:
print(transaction['Region'].unique())

['North' 'South' 'East' 'West']


In [63]:
print(transaction.groupby('Region')['Amount'].mean())

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


In [64]:
transaction.loc[
    transaction['TransactionID'] == 102,
    'Amount'
] = 165
print(transaction)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [67]:
transaction["Discount"]= transaction["Amount"]*0.10
print(transaction)

   TransactionID ProductCategory Region  Amount  discount  Discount
0            101     Electronics  North     200      20.0      20.0
1            102        Clothing  South     165      16.5      16.5
2            103     Electronics  North     300      30.0      30.0
3            104       Furniture   East     450      45.0      45.0
4            105        Clothing   West     200      20.0      20.0
5            106     Electronics  North     250      25.0      25.0
6            107       Furniture   East     300      30.0      30.0
7            108        Clothing   West     180      18.0      18.0
8            109       Furniture  South     350      35.0      35.0
9            110     Electronics  North     400      40.0      40.0


In [68]:

remove= transaction[
    transaction['TransactionID'] != 109
]
print(remove)

   TransactionID ProductCategory Region  Amount  discount  Discount
0            101     Electronics  North     200      20.0      20.0
1            102        Clothing  South     165      16.5      16.5
2            103     Electronics  North     300      30.0      30.0
3            104       Furniture   East     450      45.0      45.0
4            105        Clothing   West     200      20.0      20.0
5            106     Electronics  North     250      25.0      25.0
6            107       Furniture   East     300      30.0      30.0
7            108        Clothing   West     180      18.0      18.0
9            110     Electronics  North     400      40.0      40.0


In [69]:
transaction = transaction.drop(columns='Discount')

print(transaction)

   TransactionID ProductCategory Region  Amount  discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0
